### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ReaperMaga** [prismarin-minecraft/management#13]
- [x] Party chat and clan chat (toggleable)
- [x] Earn battlepass exp from warzone
- [x] Add insta mine tools
- [x] Disable minigun in ffa
- [x] Add /clan setmachinecount and /clan setupgradlevel
- [x] Fix bosses leash range
- [x] Fix riot shield
